cc_proto_library(
    name = "address_book_cc",
    deps = [":address_book_proto"],
    visibility = ["//visibility:public"],
)

proto_library(
    name = "address_book_proto",
    srcs = ["address_book.proto"],
)
